# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "npm" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "monthly"
    groups:
      # Group all lwc-test (aka `lwc/jest-*`) deps together since they all depend on each other
      # See: https://github.com/salesforce/lwc-test
      lwc-test:
        patterns:
          - "@lwc/jest-*"
      # Group other lwc deps together since they also all depend on each other
      # See: https://github.com/salesforce/lwc
      lwc:
        patterns:
          - "@lwc/*"
      # Non-major version bumps hopefully shouldn't break anything,
      # so let's group them together into a single PR!
      theoretically-non-breaking:
        update-types:
          - "minor"
          - "patch"
