name: Lint and unit tests

on:
    push:
        branches:
            - master
            - 'spring*'
            - 'summer*'
            - 'winter*'
    pull_request:
        branches:
            - master
            - 'spring*'
            - 'summer*'
            - 'winter*'

jobs:
    lint-unit-tests:
        runs-on: ubuntu-22.04
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Setup Node
              uses: actions/setup-node@v4
              with:
                  node-version: '20.12.1'
                  cache: 'yarn'

            - name: Install dependencies
              run: yarn install --frozen-lockfile

            - name: Check License Headers
              run: yarn check-license-headers

            - name: Check formatting
              run: yarn format:check
            
            - name: Run linter
              run: yarn lint

            - name: Run unit tests
              run: yarn test


